export const monthlyData = [
  { month: "Jan", totalBooking: 12300 },
  { month: "Feb", totalBooking: 14500 },
  { month: "Mar", totalBooking: 13400 },
  { month: "Apr", totalBooking: 12800 },
  { month: "May", totalBooking: 13700 },
  { month: "Jun", totalBooking: 15100 },
  { month: "Jul", totalBooking: 14200 },
  { month: "Aug", totalBooking: 15600 },
  { month: "Sep", totalBooking: 16300 },
  { month: "Oct", totalBooking: 17100 },
  { month: "Nov", totalBooking: 15800 },
  { month: "Dec", totalBooking: 16800 },
];
export const dashboardBookingColumnData = [
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    time: "10:00 AM",
    person: 1,
  },
  {
    name: "Alice Smith",
    email: "alice@example.com",
    branch: "Branch B",
    date: "2024-05-02",
    time: "11:30 AM",
    person: 2,
  },
  {
    name: "Bob Johnson",
    email: "bob@example.com",
    branch: "Branch C",
    date: "2024-05-03",
    time: "1:00 PM",
    person: 1,
  },
  {
    name: "Emily Brown",
    email: "emily@example.com",
    branch: "Branch A",
    date: "2024-05-04",
    time: "2:30 PM",
    person: 3,
  },
  {
    name: "Michael Lee",
    email: "michael@example.com",
    branch: "Branch B",
    date: "2024-05-05",
    time: "9:00 AM",
    person: 2,
  },
  {
    name: "Sarah Miller",
    email: "sarah@example.com",
    branch: "Branch C",
    date: "2024-05-06",
    time: "12:30 PM",
    person: 1,
  },
  {
    name: "David Wilson",
    email: "david@example.com",
    branch: "Branch A",
    date: "2024-05-07",
    time: "3:00 PM",
    person: 4,
  },
  {
    name: "Emma Davis",
    email: "emma@example.com",
    branch: "Branch B",
    date: "2024-05-08",
    time: "10:30 AM",
    person: 1,
  },
  {
    name: "James Taylor",
    email: "james@example.com",
    branch: "Branch C",
    date: "2024-05-09",
    time: "2:00 PM",
    person: 2,
  },
  {
    name: "Olivia Anderson",
    email: "olivia@example.com",
    branch: "Branch A",
    date: "2024-05-10",
    time: "11:00 AM",
    person: 3,
  },
  {
    name: "William Martinez",
    email: "william@example.com",
    branch: "Branch B",
    date: "2024-05-11",
    time: "1:30 PM",
    person: 1,
  },
  {
    name: "Sophia Clark",
    email: "sophia@example.com",
    branch: "Branch C",
    date: "2024-05-12",
    time: "4:00 PM",
    person: 2,
  },
  {
    name: "Daniel Brown",
    email: "daniel@example.com",
    branch: "Branch A",
    date: "2024-05-13",
    time: "9:30 AM",
    person: 1,
  },
  {
    name: "Isabella Scott",
    email: "isabella@example.com",
    branch: "Branch B",
    date: "2024-05-14",
    time: "12:00 PM",
    person: 3,
  },
  {
    name: "Liam White",
    email: "liam@example.com",
    branch: "Branch C",
    date: "2024-05-15",
    time: "3:30 PM",
    person: 1,
  },
  {
    name: "Ava Rodriguez",
    email: "ava@example.com",
    branch: "Branch A",
    date: "2024-05-16",
    time: "10:00 AM",
    person: 2,
  },
  {
    name: "Noah Green",
    email: "noah@example.com",
    branch: "Branch B",
    date: "2024-05-17",
    time: "1:30 PM",
    person: 1,
  },
  {
    name: "Mia Harris",
    email: "mia@example.com",
    branch: "Branch C",
    date: "2024-05-18",
    time: "4:00 PM",
    person: 4,
  },
  {
    name: "Ethan Martinez",
    email: "ethan@example.com",
    branch: "Branch A",
    date: "2024-05-19",
    time: "9:30 AM",
    person: 1,
  },
  {
    name: "Charlotte Davis",
    email: "charlotte@example.com",
    branch: "Branch B",
    date: "2024-05-20",
    time: "12:00 PM",
    person: 3,
  },
];
