export const subAdminData = [
  {
    key: 1,
    name: "John Doe",
    designation: "Manager",
    branch: "Branch 1",
  },
  {
    key: 2,
    name: "Alice Smith",
    designation: "Supervisor",
    branch: "Branch 2",
  },
  {
    key: 3,
    name: "Bob Johnson",
    designation: "Assistant",
    branch: "Branch 1",
  },
  {
    key: 4,
    name: "Emma Brown",
    designation: "Worker",
    branch: "Branch 3",
  },
  {
    key: 5,
    name: "Michael Clark",
    designation: "Manager",
    branch: "Branch 2",
  },
  {
    key: 6,
    name: "Sarah Adams",
    designation: "Supervisor",
    branch: "Branch 3",
  },
  {
    key: 7,
    name: "David Wilson",
    designation: "Assistant",
    branch: "Branch 1",
  },
  {
    key: 8,
    name: "Olivia Martinez",
    designation: "Worker",
    branch: "Branch 2",
  },
  {
    key: 9,
    name: "James Lee",
    designation: "Manager",
    branch: "Branch 3",
  },
  {
    key: 10,
    name: "Sophia White",
    designation: "Supervisor",
    branch: "Branch 1",
  },
  {
    key: 11,
    name: "William Taylor",
    designation: "Assistant",
    branch: "Branch 2",
  },
  {
    key: 12,
    name: "Charlotte Harris",
    designation: "Worker",
    branch: "Branch 3",
  },
  {
    key: 13,
    name: "Ethan Turner",
    designation: "Manager",
    branch: "Branch 1",
  },
  {
    key: 14,
    name: "Ava Clark",
    designation: "Supervisor",
    branch: "Branch 2",
  },
  {
    key: 15,
    name: "Noah Baker",
    designation: "Assistant",
    branch: "Branch 1",
  },
  {
    key: 16,
    name: "Mia Green",
    designation: "Worker",
    branch: "Branch 3",
  },
  {
    key: 17,
    name: "Liam Carter",
    designation: "Manager",
    branch: "Branch 2",
  },
  {
    key: 18,
    name: "Ella Foster",
    designation: "Supervisor",
    branch: "Branch 3",
  },
  {
    key: 19,
    name: "Benjamin Murphy",
    designation: "Assistant",
    branch: "Branch 1",
  },
  {
    key: 20,
    name: "Amelia King",
    designation: "Worker",
    branch: "Branch 2",
  },
];
