export const tableData = [
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
  {
    totalTables: 500,
    persons: "5p",
    tables: "2+2 = 4",
    Branch: "Branch 1",
  },
];
