export const transactionData = [
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
  {
    serial: 1,
    buyer: "opu vai",
    restaurantName: "king jong um",
    item: "burger",
    amount: 100,
    date: "2024-10-13",
  },
];
